# Ruby and Rails styling
plugins:
  - rubocop-rails

require:
  - rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.4
  Exclude:
    - 'bin/**/*'
    - 'db/**/*'
    - 'config/**/*'
    - 'vendor/**/*'
    - 'node_modules/**/*'

# Overwrite or add rules to create your own house style
Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: true

Layout/LineLength:
  Max: 120

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'config/**/*'

Metrics/AbcSize:
  Max: 30

Metrics/MethodLength:
  Max: 20

Metrics/CyclomaticComplexity:
  Max: 15

Metrics/PerceivedComplexity:
  Max: 15

RSpec/MultipleExpectations:
  Max: 10

RSpec/ExampleLength:
  Max: 10

Rails/ActionOrder:
  Enabled: false
