# SQLite. Versions 3.8.0 and up are supported.
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem "sqlite3"
#
default: &default
  adapter: sqlite3
  pool: <%= Settings.rails.max_threads %>
  timeout: 5000

development:
  primary: &primary_development
    <<: *default
    database: storage/development.sqlite3
  cache:
    <<: *primary_development
    database: storage/development_cache.sqlite3
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_development
    database: storage/development_queue.sqlite3
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_development
    database: storage/development_cable.sqlite3
    migrations_paths: db/cable_migrate

test:
  primary: &primary_test
    <<: *default
    database: storage/test.sqlite3
  cache:
    <<: *primary_test
    database: storage/test_cache.sqlite3
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_test
    database: storage/test_queue.sqlite3
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_test
    database: storage/test_cable.sqlite3
    migrations_paths: db/cable_migrate

production:
  primary: &primary_production
    <<: *default
    database: storage/production.sqlite3
  cache:
    <<: *primary_production
    database: storage/production_cache.sqlite3
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: storage/production_queue.sqlite3
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: storage/production_cable.sqlite3
    migrations_paths: db/cable_migrate