# Environment variables for word-complexity-api

# Job processing concurrency
JOB_CONCURRENCY=1

# Rails environment
RAILS_ENV=development

# Database configuration
DATABASE_URL=postgresql://localhost/word_complexity_api_development

# Redis configuration (for job queues)
REDIS_URL=redis://localhost:6379/0

# API configuration
API_VERSION=v1

# Logging
LOG_LEVEL=info
